### ISSUE TITLE
Issue when image is smaller than target size

### ISSUE THREAD

**Issue by alanpich** [alanpich/tvImagePlus#14]
Cropper is unusable when uploaded image is smaller than target crop size

**Comment by yuka123** [comment]
That solution is ok but, Its not ideal tbh, more smart would be to use phpthumb to resize images to correct size if too small ..

**Comment by alanpich** [comment]
Not sure if smart is the right word there... Would you want the system automatically up-scaling your source images?!

**Comment by yuka123** [comment]
Well alanpich, I understand what you mean, and proper way is to manually always gurantee that images will have correct sizes and then upload them and use them in imgtv+.. but in reality that is not so often the case. Specially when dealing with users.. I mean what if many images are too smal.. but user wants to use them.. Then I must manually correct after them, which is not somethign I would like to keep doing. So yeah I would rather see up-scaling of the source, or even making a copy of upscaled source and leaving the original.

**Comment by Glidias** [comment]
Hmm...if they did upscale the images though, some warning could be used (or a template variable Input setting), otherwise, the client might be blissfully ignorant in such cases.

Also, why not allow the crop rectangle to exceed out of the image bounds in such a case rather than upscaling? It might not necessarily require up-scaling but simply dragging the crop rectangle over void "bgcolor" regions. Currently, this isn't supported with the strict dimension checks, which is fine for me now but may be required for some other users. Fallback PHP thumb Input Option settings (excluding the dimensions) could be possible, i guess....so, rather than showing the "Image Too Small" window,  it could use the fallback and maybe give a warning that the editable image is modified from the original.
